// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /Users/sakamoto/hs_cosmic/./run.h;
#pragma link C++ defined_in "/Users/sakamoto/hs_cosmic/./run.cc";

#endif
